#!/usr/bin/env bash

cmd=$1

if [ "$cmd" == "" ]; then
    echo "Use '$0 --install' to actually install the service"
    exit
fi

if [ ! "$cmd" == "--install" ]; then
    echo "Unknown command '$cmd'"
    exit
fi

# ------------------------------------------------------------------------------
echo Install dbus profile
cp etc-dbus-1/de.sgdw.linux.glight.conf /etc/dbus-1/de.sgdw.linux.glight.conf
# ------------------------------------------------------------------------------
echo Install init script
src=etc-init.d/glight
target=/etc/init.d/glight
cp "$src" "$target"
chown root:root "$target"
chmod 755 "$target"

# ------------------------------------------------------------------------------
echo Install lib
src=
target=/usr/local/lib/glight
if [ ! -d "$target" ]; then
    mkdir target
    chown root:root "$target"
    chmod 755 "$target"
fi

echo Copy files
cp -v ../glight.* /usr/local/lib/glight/
cp -v ../glight_*.* /usr/local/lib/glight/
rm -v /usr/local/lib/glight/*.pyc

target=/usr/local/lib/glight/glight.py
chown root:root "$target"
chmod 755 "$target"

target=/usr/local/lib/glight/glight_ui.py
chown root:root "$target"
chmod 755 "$target"

# ------------------------------------------------------------------------------
echo Install runlevel
src=../init.d/glight
# ----------------------------
echo Setup runlevel 5
cd /etc/rc5.d
target=S08glight
if [ ! -f "$target" ]; then
    ln -s "$src" "$target"
fi
# ----------------------------
echo Setup runlevel 0
cd /etc/rc0.d
target=K01glight
if [ ! -f "$target" ]; then
    ln -s "$src" "$target"
fi
# ----------------------------
echo Setup runlevel 6
cd /etc/rc6.d
target=K01glight
if [ ! -f "$target" ]; then
    ln -s "$src" "$target"
fi

# ------------------------------------------------------------------------------
echo Restart service
/etc/init.d/glight restart
# ------------------------------------------------------------------------------
echo Done