#!/bin/sh
### BEGIN INIT INFO
# Provides:          glight
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       GLight service
### END INIT INFO

name=glight

if [ -f "/usr/local/lib/$name/$name.py" ]; then
    SCRIPT="/usr/local/lib/$name/$name.py"
elif [ -f "/usr/lib/$name/$name.py" ]; then
    SCRIPT="/usr/lib/$name/$name.py"
else
    echo "$name lib not found"
    exit 1
fi

RUNAS=root

PIDFILE=/var/run/$name.pid
LOGFILE=/dev/nul # /var/log/<NAME>.log

STATEDIR=/var/glight
STATEFILE=$STATEDIR/glight.gstate

if [ ! -d "$STATEDIR" ]; then
    mkdir "$STATEDIR"
fi

start() {
    if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
        echo 'Service already running' >&2
        return 1
    fi
    echo 'Starting service…' >&2
    local CMD="$SCRIPT --service --state-file \"$STATEFILE\" --load-state &> \"$LOGFILE\" & echo \$!"
    su -c "$CMD" $RUNAS > "$PIDFILE"
    echo 'Service started' >&2
}

stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo 'Service not running' >&2
        return 1
    fi
    echo 'Stopping service…' >&2
    kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
    echo 'Service stopped' >&2
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac