#!/bin/bash
### BEGIN INIT INFO
# Provides:          glight
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       GLight service
### END INIT INFO

name=glight

config_file="/etc/glight.conf"

if [ ! -f "$config_file" ]; then
    echo "Error: Config '$config_file' not found. Aborting!"
    exit 1
fi

source "$config_file"

if [ "$glight_path" == "" ]; then
    echo "Error: Glight path is not set in '$config_file'!"
    exit 1
fi

SCRIPT="$glight_path/$name/$name.py"
if [ ! -f "$SCRIPT" ]; then
    echo "Error: GLight app '$SCRIPT' not found"
    exit 1
fi

STATEDIR=/var/glight

if [ ! "$glight_state_path" == "" ]; then
    STATEDIR="$glight_state_path"
fi

STATEFILE=$STATEDIR/glight.gstate

RUNAS=root

PIDFILE=/var/run/$name.pid
LOGFILE=/dev/nul # /var/log/<NAME>.log

if [ ! "$glight_log_file" == "" ]; then
    LOGFILE="$glight_log_file"
fi

if [ ! -d "$STATEDIR" ]; then
    mkdir "$STATEDIR"
fi

start() {
    if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
        echo "Service $name already running" >&2
        return 1
    fi
    echo "Starting $name service" >&2
    local CMD="$SCRIPT --service --state-file \"$STATEFILE\" --load-state &> \"$LOGFILE\" & echo \$!"
    su -c "$CMD" $RUNAS > "$PIDFILE"
    echo "Service $name started" >&2
}

stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo "Service $name not running" >&2
        return 1
    fi
    echo "Stopping $name service" >&2
    kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
    echo "Service $name stopped" >&2
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac